@extends('layouts.app')
@section('content')
@php
$change = function ($current, $previous) { if ((float) $previous === 0.0) return (float) $current > 0 ? 100 : 0; return round(((float) $current - (float) $previous) / (float) $previous * 100, 1); };
$reqChange = $change($today->requests, $yesterday->requests); $tokenChange = $change($today->input_tokens + $today->output_tokens, $yesterday->input_tokens + $yesterday->output_tokens); $costChange = $change($today->cost, $yesterday->cost); $errorRate = $today->requests ? round($today->errors / $today->requests * 100, 2) : 0; $maxModel = max(1, (int) ($topModels->max('tokens') ?? 1));
@endphp
<style>
.ov-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.ov-stat{padding:17px}.ov-label{font-size:12px;color:var(--muted);font-weight:700;text-transform:uppercase;letter-spacing:.04em}.ov-value{font-size:24px;font-weight:800;margin:7px 0 3px}.ov-sub{font-size:12px;color:var(--muted)}.ov-up{color:#16a34a}.ov-down{color:#dc2626}.ov-main{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(280px,.8fr);gap:16px}.ov-chart{height:250px}.ov-chart svg{width:100%;height:100%;overflow:visible}.ov-gridline{stroke:var(--line);stroke-width:1}.ov-axis{fill:var(--muted);font-size:10px}.ov-today{fill:none;stroke:#2563eb;stroke-width:3}.ov-yesterday{fill:none;stroke:#94a3b8;stroke-width:2;stroke-dasharray:6 5}.ov-point{fill:var(--card);stroke:#2563eb;stroke-width:2}.ov-legend{display:flex;gap:14px;font-size:12px;color:var(--muted)}.ov-legend i{display:inline-block;width:18px;height:3px;margin-right:5px;vertical-align:middle}.ov-kpi{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ov-mini{background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:12px}.ov-mini strong{display:block;font-size:18px;margin-top:4px}.ov-rank{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;padding:10px 0;border-bottom:1px solid var(--line)}.ov-rank:last-child{border:0}.ov-name{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ov-track{height:7px;background:var(--line);border-radius:8px;overflow:hidden;margin:5px 0}.ov-fill{height:100%;background:#2563eb;border-radius:8px}.ov-actions{display:flex;gap:10px;flex-wrap:wrap}.ov-actions .btn{margin:0}@media(max-width:1000px){.ov-stats{grid-template-columns:repeat(2,1fr)}.ov-main{grid-template-columns:1fr}}@media(max-width:600px){.ov-stats{grid-template-columns:1fr}}
</style>
<div class="top"><div><h2>{{ __('dashboard.overview.heading') }}</h2><p>{{ __('dashboard.overview.subtitle_dash') }}</p></div><span class="pill">Base URL: https://api.azkia.cloud/v1</span></div>
<div class="hero"><h2>{{ __('dashboard.overview.welcome', ['name' => $user->name]) }}</h2><p>{{ __('dashboard.overview.welcome_text') }}</p><div class="ov-actions"><a class="btn" href="{{ route('keys') }}">{{ __('dashboard.overview.manage_keys') }}</a><a class="btn secondary" href="{{ route('usage') }}">{{ __('dashboard.overview.view_usage') }}</a><a class="btn secondary" href="{{ route('payments.create') }}">{{ __('dashboard.overview.topup_balance') }}</a></div></div>
<div class="ov-stats section">
<div class="card ov-stat"><div class="ov-label">{{ __('dashboard.overview.balance_available') }}</div><div class="ov-value">{{ format_idr_usd($user->balance) }}</div><div class="ov-sub">{{ __('dashboard.overview.reserved_keys', ['amount' => format_idr_usd($user->reserved_balance), 'count' => $activeKeys]) }}</div></div>
<div class="card ov-stat"><div class="ov-label">{{ __('dashboard.overview.requests_today') }}</div><div class="ov-value">{{ number_format($today->requests) }}</div><div class="ov-sub {{ $reqChange >= 0 ? 'ov-up' : 'ov-down' }}">{{ __('dashboard.overview.vs_yesterday', ['arrow' => $reqChange >= 0 ? '↑' : '↓', 'percent' => abs($reqChange), 'count' => number_format($yesterday->requests)]) }}</div></div>
<div class="card ov-stat"><div class="ov-label">{{ __('dashboard.overview.tokens_today') }}</div><div class="ov-value">{{ format_compact_number($today->input_tokens + $today->output_tokens) }}</div><div class="ov-sub {{ $tokenChange >= 0 ? 'ov-up' : 'ov-down' }}">{{ __('dashboard.overview.tokens_sub', ['arrow' => $tokenChange >= 0 ? '↑' : '↓', 'percent' => abs($tokenChange), 'input' => format_compact_number($today->input_tokens), 'output' => format_compact_number($today->output_tokens)]) }}</div></div>
<div class="card ov-stat"><div class="ov-label">{{ __('dashboard.overview.cost_today') }}</div><div class="ov-value">{{ format_idr_usd($today->cost) }}</div><div class="ov-sub {{ $costChange <= 0 ? 'ov-up' : 'ov-down' }}">{{ __('dashboard.overview.vs_yesterday_pct', ['arrow' => $costChange >= 0 ? '↑' : '↓', 'percent' => abs($costChange)]) }}</div></div>
</div>
<div class="ov-main section"><div class="card"><div class="top" style="margin-bottom:6px"><div><h3>{{ __('dashboard.overview.traffic_hourly') }}</h3><p>{{ __('dashboard.overview.today_vs_yesterday') }}</p></div><div class="ov-legend"><span><i style="background:#2563eb"></i>{{ __('dashboard.overview.today') }}</span><span><i style="background:#94a3b8"></i>{{ __('dashboard.overview.yesterday') }}</span></div></div><div id="overview-chart" class="ov-chart" data-points='@json($hourly)'><svg viewBox="0 0 700 245" preserveAspectRatio="none"></svg></div></div><div class="card"><h3>{{ __('dashboard.overview.health_today') }}</h3><div class="ov-kpi"><div class="ov-mini"><span class="ov-sub">{{ __('dashboard.overview.success_rate') }}</span><strong>{{ $today->requests ? round(($today->requests-$today->errors)/$today->requests*100, 2) : 100 }}%</strong></div><div class="ov-mini"><span class="ov-sub">{{ __('dashboard.overview.error_rate') }}</span><strong>{{ $errorRate }}%</strong></div><div class="ov-mini"><span class="ov-sub">{{ __('dashboard.overview.avg_latency') }}</span><strong>{{ number_format($today->avg_latency) }} ms</strong></div></div><h3 style="margin-top:20px">{{ __('dashboard.overview.last_7_days') }}</h3><p>{{ __('dashboard.overview.summary_7', ['requests' => number_format($sevenDays->requests), 'tokens' => format_compact_number($sevenDays->input_tokens + $sevenDays->output_tokens)]) }}</p><p>{{ __('dashboard.overview.summary_7_cost', ['cost' => format_idr_usd($sevenDays->cost), 'count' => number_format($sevenDays->errors)]) }}</p></div></div>
<div class="grid2 section"><div class="card"><h3>{{ __('dashboard.overview.top_models_7') }}</h3>@forelse($topModels as $row)<div class="ov-rank"><div><div class="ov-name">{{ $row->model }}</div><div class="ov-track"><div class="ov-fill" style="width:{{ round($row->tokens/$maxModel*100) }}%"></div></div><div class="ov-sub">{{ __('dashboard.overview.per_model_7', ['count' => number_format($row->requests), 'cost' => format_idr_usd($row->cost)]) }}</div></div><strong>{{ format_compact_number($row->tokens) }}</strong></div>@empty<p class="muted">{{ __('dashboard.overview.no_usage') }}</p>@endforelse</div><div class="card"><h3>{{ __('dashboard.overview.recent_keys') }}</h3><div class="table-wrap"><table><tr><th>{{ __('dashboard.overview.name') }}</th><th>{{ __('dashboard.overview.usage_7_days') }}</th><th>{{ __('dashboard.common.status') }}</th></tr>@forelse($apiKeys as $key)@php($stat=$keyStats->get($key->id))<tr><td>{{ $key->name }}<br><span class="muted">{{ $key->prefix }}</span></td><td>{{ __('dashboard.overview.req_short', ['count' => number_format($stat->requests ?? 0)]) }}<br><span class="muted">{{ __('dashboard.overview.token_short', ['count' => format_compact_number($stat->tokens ?? 0)]) }}</span></td><td><span class="badge {{ $key->is_active ? 'green' : 'red' }}">{{ $key->is_active ? __('dashboard.common.active') : __('dashboard.common.inactive') }}</span></td></tr>@empty<tr><td colspan="3" class="muted">{{ __('dashboard.overview.no_keys') }}</td></tr>@endforelse</table></div></div></div>
<div class="section card"><div class="top"><div><h3>{{ __('dashboard.overview.recent_requests') }}</h3></div><a class="btn secondary" href="{{ route('usage') }}">{{ __('dashboard.overview.all_requests') }}</a></div><div class="table-wrap"><table><tr><th>{{ __('dashboard.common.time') }}</th><th>{{ __('dashboard.overview.model_endpoint') }}</th><th>{{ __('dashboard.common.tokens') }}</th><th>{{ __('dashboard.common.cost') }}</th><th>{{ __('dashboard.pages.usage.latency') }}</th><th>{{ __('dashboard.common.status') }}</th></tr>@forelse($recentUsage as $log)<tr><td>{{ $log->created_at?->locale(app()->getLocale())->translatedFormat('d M H:i') }}</td><td>{{ $log->model }}<br><span class="muted">{{ $log->endpoint }}</span></td><td>{{ number_format($log->input_tokens) }} {{ __('dashboard.overview.in') }}<br>{{ number_format($log->output_tokens) }} {{ __('dashboard.overview.out') }}</td><td>{{ format_idr_from_usd($log->cost) }}</td><td>{{ $log->latency_ms !== null ? number_format($log->latency_ms).' ms' : '—' }}</td><td><span class="badge {{ ($log->status_code ?? 500) >= 400 ? 'red' : 'green' }}">{{ $log->status_code ?? '—' }}</span></td></tr>@empty<tr><td colspan="6" class="muted">{{ __('dashboard.overview.no_requests') }}</td></tr>@endforelse</table></div></div>
<script>(function(){var el=document.getElementById('overview-chart');if(!el)return;var d=JSON.parse(el.dataset.points||'[]'),svg=el.querySelector('svg'),w=700,h=245,l=36,r=10,t=14,b=27,max=Math.max(1,...d.map(x=>Math.max(x.today,x.yesterday))),uw=w-l-r,uh=h-t-b,c=k=>d.map((x,i)=>({x:l+i*uw/23,y:t+uh-x[k]/max*uh})),p=a=>a.map((x,i)=>(i?'L':'M')+x.x.toFixed(1)+' '+x.y.toFixed(1)).join(' '),a=c('today'),z=c('yesterday'),html='';[0,.25,.5,.75,1].forEach(q=>{var y=t+uh*q;html+='<line class="ov-gridline" x1="'+l+'" y1="'+y+'" x2="'+(w-r)+'" y2="'+y+'"/><text class="ov-axis" x="'+(l-5)+'" y="'+(y+3)+'" text-anchor="end">'+Math.round(max*(1-q))+'</text>'});d.forEach((x,i)=>{if(i%3===0)html+='<text class="ov-axis" x="'+a[i].x+'" y="'+(h-6)+'" text-anchor="middle">'+x.label+'</text>'});html+='<path class="ov-yesterday" d="'+p(z)+'"/><path class="ov-today" d="'+p(a)+'"/>';a.forEach((x,i)=>html+='<circle class="ov-point" cx="'+x.x+'" cy="'+x.y+'" r="3"><title>'+@json(__('dashboard.overview.chart_title')).replace(':label', d[i].label).replace(':count', d[i].today)+'</title></circle>');svg.innerHTML=html})();</script>
@endsection
