@extends('layouts.app')

@section('content')
<style>
    .tools-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}
    .tool-card{display:flex;flex-direction:column;background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:16px;box-shadow:var(--shadow-card)}
    .tool-card h4{margin:0 0 2px;font-size:14px;font-weight:750;letter-spacing:-.01em}
    .tool-card .cat{color:var(--muted);font-size:11.5px;margin:0 0 10px}
    .tool-card .key{margin:0;padding:10px 12px;font-size:11.5px;line-height:1.6}
    .tool-card p.how{margin:0;color:var(--muted);font-size:12.5px;line-height:1.6}
    .tool-card code{background:var(--soft);border:1px solid var(--line);border-radius:6px;padding:1px 5px;font-size:12px;color:var(--ink);font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
    @media(max-width:999.98px){.tools-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
    @media(max-width:639.98px){.tools-grid{grid-template-columns:minmax(0,1fr)}}
</style>
<div class="top"><div><h2>{{ __('dashboard.pages.docs.heading') }}</h2><p>{{ __('dashboard.pages.docs.subtitle') }}</p></div><span class="pill">OpenAI Compatible</span></div>
<div class="grid2">
    <div class="card"><h3>{{ __('dashboard.pages.docs.base_url') }}</h3><div class="key">https://api.azkia.cloud/v1</div><p class="muted">{{ __('dashboard.pages.docs.base_hint') }}</p></div>
    <div class="card"><h3>{{ __('dashboard.pages.docs.authentication') }}</h3><div class="key">Authorization: Bearer azkia_xxxxx</div><p class="muted">{{ __('dashboard.pages.docs.auth_hint') }}</p></div>
</div>
<div class="section card"><h3>{{ __('dashboard.pages.docs.python') }}</h3><div class="key">from openai import OpenAI<br><br>client = OpenAI(base_url="https://api.azkia.cloud/v1", api_key="azkia_xxxxx")<br><br>response = client.chat.completions.create(<br>&nbsp;&nbsp;model="deepseek/deepseek-v4-flash",<br>&nbsp;&nbsp;messages=[{"role": "user", "content": "Hello!"}]<br>)<br>print(response.choices[0].message.content)</div></div>
<div class="section card"><h3>{{ __('dashboard.pages.docs.curl') }}</h3><div class="key">curl https://api.azkia.cloud/v1/chat/completions \<br>&nbsp;&nbsp;-H "Authorization: Bearer azkia_xxxxx" \<br>&nbsp;&nbsp;-H "Content-Type: application/json" \<br>&nbsp;&nbsp;-d '{"model":"deepseek/deepseek-v4-flash","messages":[{"role":"user","content":"Hello"}]}'</div></div>
<div class="section card"><h3>{{ __('dashboard.pages.docs.nodejs') }}</h3><div class="key">import OpenAI from "openai";<br><br>const client = new OpenAI({<br>&nbsp;&nbsp;baseURL: "https://api.azkia.cloud/v1",<br>&nbsp;&nbsp;apiKey: "azkia_xxxxx",<br>});<br><br>const res = await client.chat.completions.create({<br>&nbsp;&nbsp;model: "deepseek/deepseek-v4-flash",<br>&nbsp;&nbsp;messages: [{ role: "user", content: "Hello!" }],<br>});<br>console.log(res.choices[0].message.content);</div></div>
<div class="section card"><h3>{{ __('dashboard.pages.docs.tools.heading') }}</h3><p class="muted" style="margin:0 0 14px">{{ __('dashboard.pages.docs.tools.intro') }}</p><div class="tools-grid">
    <div class="tool-card"><h4>OpenCode</h4><p class="cat">{{ __('dashboard.pages.docs.tools.cat_agent_terminal') }}</p><div class="key">{<br>&nbsp;&nbsp;"provider": {<br>&nbsp;&nbsp;&nbsp;&nbsp;"azkia": {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"npm": "&#64;ai-sdk/openai-compatible",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"name": "Azkia Router",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"options": {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"baseURL": "https://api.azkia.cloud/v1",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"apiKey": "azkia_xxx"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"models": {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"deepseek/deepseek-v4-flash": {}<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;}<br>}</div></div>
    <div class="tool-card"><h4>Aider</h4><p class="cat">{{ __('dashboard.pages.docs.tools.cat_agent_terminal') }}</p><div class="key">aider --openai-api-base https://api.azkia.cloud/v1 \<br>&nbsp;&nbsp;--openai-api-key azkia_xxx \<br>&nbsp;&nbsp;--model deepseek/deepseek-v4-flash</div></div>
    <div class="tool-card"><h4>Cline</h4><p class="cat">{{ __('dashboard.pages.docs.tools.cat_vscode') }}</p><p class="how">{!! __('dashboard.pages.docs.tools.how_cline', ['url' => 'https://api.azkia.cloud/v1']) !!}</p></div>
    <div class="tool-card"><h4>Roo Code</h4><p class="cat">{{ __('dashboard.pages.docs.tools.cat_vscode') }}</p><p class="how">{!! __('dashboard.pages.docs.tools.how_roo', ['url' => 'https://api.azkia.cloud/v1']) !!}</p></div>
    <div class="tool-card"><h4>Continue</h4><p class="cat">{{ __('dashboard.pages.docs.tools.cat_vscode_jetbrains') }}</p><p class="how">{!! __('dashboard.pages.docs.tools.how_continue', ['url' => 'https://api.azkia.cloud/v1']) !!}</p></div>
    <div class="tool-card"><h4>Cherry Studio</h4><p class="cat">{{ __('dashboard.pages.docs.tools.cat_desktop') }}</p><p class="how">{!! __('dashboard.pages.docs.tools.how_cherry', ['url' => 'https://api.azkia.cloud/v1']) !!}</p></div>
    <div class="tool-card"><h4>Chatbox</h4><p class="cat">{{ __('dashboard.pages.docs.tools.cat_chat') }}</p><p class="how">{!! __('dashboard.pages.docs.tools.how_chatbox', ['url' => 'https://api.azkia.cloud/v1']) !!}</p></div>
    <div class="tool-card"><h4>Open WebUI</h4><p class="cat">{{ __('dashboard.pages.docs.tools.cat_web') }}</p><p class="how">{!! __('dashboard.pages.docs.tools.how_webui', ['url' => 'https://api.azkia.cloud/v1']) !!}</p></div>
    <div class="tool-card"><h4>LibreChat</h4><p class="cat">{{ __('dashboard.pages.docs.tools.cat_web') }}</p><p class="how">{!! __('dashboard.pages.docs.tools.how_librechat', ['url' => 'https://api.azkia.cloud/v1']) !!}</p></div>
</div></div>
<div class="section card"><h3>{{ __('dashboard.pages.docs.streaming') }}</h3><p class="muted" style="margin:0 0 8px">{{ __('dashboard.pages.docs.streaming_hint') }}</p><div class="key">curl https://api.azkia.cloud/v1/chat/completions \<br>&nbsp;&nbsp;-H "Authorization: Bearer azkia_xxxxx" \<br>&nbsp;&nbsp;-H "Content-Type: application/json" \<br>&nbsp;&nbsp;-d '{"model":"deepseek/deepseek-v4-flash","stream":true,"messages":[{"role":"user","content":"Hello"}]}'</div></div>
<div class="section card"><h3>{{ __('dashboard.pages.docs.endpoints') }}</h3><div class="table-wrap"><table><tr><th>{{ __('dashboard.pages.docs.method') }}</th><th>{{ __('dashboard.pages.docs.path') }}</th><th>{{ __('dashboard.pages.docs.description') }}</th></tr><tr><td>GET</td><td>/v1/models</td><td>{{ __('dashboard.pages.docs.list_models') }}</td></tr><tr><td>POST</td><td>/v1/chat/completions</td><td>{{ __('dashboard.pages.docs.chat') }}</td></tr><tr><td>POST</td><td>/v1/completions</td><td>{{ __('dashboard.pages.docs.text_completions') }}</td></tr><tr><td>POST</td><td>/v1/embeddings</td><td>{{ __('dashboard.pages.docs.embeddings') }}</td></tr></table></div></div>
<div class="section card"><h3>{{ __('dashboard.pages.docs.errors') }}</h3><div class="table-wrap"><table><tr><th>{{ __('dashboard.common.status') }}</th><th>{{ __('dashboard.pages.docs.meaning') }}</th></tr><tr><td>400</td><td>{{ __('dashboard.pages.docs.err_400') }}</td></tr><tr><td>401</td><td>{{ __('dashboard.pages.docs.err_401') }}</td></tr><tr><td>402</td><td>{{ __('dashboard.pages.docs.err_402') }}</td></tr><tr><td>403</td><td>{{ __('dashboard.pages.docs.err_403') }}</td></tr><tr><td>404</td><td>{{ __('dashboard.pages.docs.err_404') }}</td></tr><tr><td>429</td><td>{{ __('dashboard.pages.docs.err_429') }}</td></tr><tr><td>503</td><td>{{ __('dashboard.pages.docs.err_503') }}</td></tr></table></div></div>
@endsection
