@extends('layouts.app')
@section('content')
<div class="top"><div><h2>Billing Monitoring</h2><p>Observabilitas read-only reservation dan settlement billing.</p></div><span class="pill">READ ONLY</span></div>
@include('admin._alerts')
<div class="grid"><div class="card"><span class="muted">Active</span><div class="metric">{{ number_format($stats['active_count']) }}</div><small>${{ number_format($stats['active_cost'], 6) }} · {{ number_format($stats['active_tokens']) }} token</small></div><div class="card"><span class="muted">Aged &gt;15m / Retry due</span><div class="metric">{{ $stats['aged'] }} / {{ $stats['retry_due'] }}</div></div><div class="card"><span class="muted">Retry exhausted</span><div class="metric">{{ $stats['retry_exhausted'] }}</div></div><div class="card"><span class="muted">Reserved discrepancy</span><div class="metric">{{ $stats['discrepancy_count'] }}</div><small>${{ number_format($stats['discrepancy_value'], 6) }}</small></div></div>
<div class="grid section">@foreach(['settled','partial','released','failed'] as $status)<div class="card"><span class="muted">{{ ucfirst($status) }} 24h</span><div class="metric">{{ $stats[$status] }}</div></div>@endforeach</div>
<div class="card section compact"><form method="get"><div class="grid3"><div><label>Status</label><input name="status" value="{{ request('status') }}"></div><div><label>Cari UUID/upstream/email</label><input name="search" value="{{ request('search') }}"></div><div><label>Model</label><select name="model"><option value="">Semua</option>@foreach($models as $model)<option value="{{ $model }}" @selected(request('model') === $model)>{{ $model }}</option>@endforeach</select></div><div><label>Usia minimum (menit)</label><input type="number" min="1" max="10080" name="age" value="{{ request('age') }}"></div><div><label>Retry</label><select name="retry"><option value="">Semua</option>@foreach(['due'=>'Due','scheduled'=>'Scheduled','exhausted'=>'Exhausted'] as $value=>$label)<option value="{{ $value }}" @selected(request('retry') === $value)>{{ $label }}</option>@endforeach</select></div></div><button>Terapkan</button> <a class="btn secondary" href="{{ route('admin.billing-monitoring.index') }}">Reset</a></form></div>
<div class="section table-wrap"><table><thead><tr><th>Event</th><th>User / Key</th><th>Model</th><th>Reservation / Actual</th><th>Status</th><th>Retry</th><th>Waktu</th></tr></thead><tbody>@forelse($events as $event)<tr><td><a href="{{ route('admin.billing-monitoring.show', $event) }}"><strong>{{ $event->id }}</strong></a><br><span class="muted">{{ $event->upstream_request_id ?: '—' }}</span></td><td>{{ $event->user?->email ?: '—' }}<br><span class="muted">{{ $event->apiKey?->name ?: '—' }}</span></td><td>{{ $event->model }}</td><td>${{ $event->reserved_cost }} / ${{ $event->cost ?? '—' }}<br>{{ number_format($event->reserved_tokens) }} / {{ number_format(($event->input_tokens ?? 0)+($event->output_tokens ?? 0)) }} token</td><td><span class="badge">{{ $event->status }}</span></td><td>{{ $event->retry_count }}<br><span class="muted">{{ $event->next_retry_at ?: '—' }}</span></td><td>{{ $event->created_at }}</td></tr>@empty<tr><td colspan="7" class="muted">Tidak ada event.</td></tr>@endforelse</tbody></table></div>{{ $events->links() }}
@endsection
