@extends('layouts.app')

@section('content')
<div class="top"><div><h2>Kode Redeem</h2><p>Generate dan kelola batch kode saldo USD.</p></div></div>
@include('admin._alerts')
<div class="card">
<h3>Generate Batch</h3>
@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<form method="post" action="{{ route('admin.redeem-codes.store') }}">@csrf
<input type="hidden" name="generation_idempotency" value="{{ old('generation_idempotency', (string) Illuminate\Support\Str::uuid()) }}">
<div class="form-row"><div><label class="muted">Label (opsional)</label><input name="label" value="{{ old('label') }}" maxlength="100"><p class="muted" style="margin:-4px 0 10px;font-size:12px">Nama batch untuk memudahkan identifikasi kode.</p></div><div><label class="muted">Jumlah kode</label><input type="number" name="quantity" min="1" max="500" value="{{ old('quantity', 1) }}" required><p class="muted" style="margin:-4px 0 10px;font-size:12px">Jumlah kode unik yang dibuat, maksimal 500 kode.</p></div></div>
<div class="form-row"><div><label class="muted">Saldo USD per redeem</label><input name="amount" inputmode="decimal" value="{{ old('amount') }}" required><p class="muted" style="margin:-4px 0 10px;font-size:12px">Saldo USD yang ditambahkan setiap kali kode berhasil digunakan.</p></div><div><label class="muted">Kedaluwarsa (opsional)</label><input type="datetime-local" name="expires_at" value="{{ old('expires_at') }}"><p class="muted" style="margin:-4px 0 10px;font-size:12px">Kosongkan jika kode tidak memiliki batas waktu.</p></div></div>
<div class="grid3"><div><label class="muted">Maks total per kode</label><input type="number" name="max_total_uses" min="1" value="{{ old('max_total_uses', 1) }}" required><p class="muted" style="margin:-4px 0 10px;font-size:12px">Batas seluruh penggunaan untuk setiap kode.</p></div><div><label class="muted">Maks per akun</label><input type="number" name="max_uses_per_account" min="1" value="{{ old('max_uses_per_account', 1) }}" required><p class="muted" style="margin:-4px 0 10px;font-size:12px">Batas penggunaan kode yang sama oleh satu akun.</p></div><div><label class="muted">Maks per IP</label><input type="number" name="max_uses_per_ip" min="1" value="{{ old('max_uses_per_ip', 1) }}" required><p class="muted" style="margin:-4px 0 10px;font-size:12px">Batas penggunaan kode yang sama dari satu alamat IP.</p></div></div>
<label class="muted">Eligible user</label><select name="eligible_users" required><option value="all" @selected(old('eligible_users', 'all') === 'all')>Semua akun</option><option value="topup" @selected(old('eligible_users') === 'topup')>Hanya akun yang sudah pernah top up</option></select><p class="muted" style="margin:-4px 0 10px;font-size:12px">Pilih semua akun atau batasi kode untuk akun yang memiliki transaksi top up berhasil.</p>
<label class="muted">Password saat ini</label><input type="password" name="current_password" autocomplete="current-password" required><p class="muted" style="margin:-4px 0 10px;font-size:12px">Konfirmasi password admin untuk mengizinkan pembuatan kode.</p>
<button>Generate Kode</button>
</form>
</div>
<div class="section table-wrap"><table><thead><tr><th>Batch</th><th>Saldo</th><th>Eligible</th><th>Kode / Penggunaan</th><th>Kedaluwarsa</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($batches as $batch)<tr><td>{{ $batch->label ?: '#'.$batch->id }}<br><span class="muted">{{ $batch->created_at }}</span></td><td>${{ $batch->amount }}</td><td>{{ $batch->eligible_users === 'topup' ? 'Pernah top up' : 'Semua akun' }}</td><td>{{ $batch->codes_count }} / {{ $batch->codes_sum_uses_count ?? 0 }}</td><td>{{ $batch->expires_at ?: '—' }}</td><td><span class="badge {{ $batch->is_active ? 'green' : 'red' }}">{{ $batch->is_active ? 'aktif' : 'nonaktif' }}</span></td><td>@if($batch->is_active)<form method="post" action="{{ route('admin.redeem-codes.batches.disable', $batch) }}">@csrf @method('patch')<button class="danger">Disable batch</button></form>@endif @foreach($batch->codes as $code)<div style="margin-top:6px">••••{{ $code->code_hint }} · {{ $code->uses_count }} use @if($code->is_active)<form style="display:inline" method="post" action="{{ route('admin.redeem-codes.codes.disable', $code) }}">@csrf @method('patch')<button class="secondary">Disable</button></form>@endif</div>@endforeach</td></tr>@empty<tr><td colspan="7" class="muted">Belum ada batch.</td></tr>@endforelse</tbody></table></div>
{{ $batches->links() }}
@endsection
