<?php

$id = require __DIR__.'/../id/dashboard.php';

$overrides = [
    'titles' => ['dashboard' => 'Overview', 'keys' => 'API Keys', 'usage' => 'Usage', 'billing' => 'Billing', 'models' => 'Models', 'plans' => 'Plans', 'status' => 'Status', 'leaderboard' => 'Leaderboard', 'docs' => 'Docs', 'inbox' => 'Inbox', 'settings' => 'Settings', 'topup' => 'Top Up Balance', 'payment' => 'Payment Details', 'api_health' => 'API Health', 'default' => 'Dashboard'],
    'nav' => ['menu' => 'Menu', 'section_main' => 'Main', 'section_services' => 'Models & Services', 'section_billing' => 'Billing', 'section_help' => 'Help', 'section_account' => 'Account', 'overview' => 'Overview', 'keys' => 'API Keys', 'usage' => 'Usage', 'billing' => 'Billing', 'models' => 'Models', 'plans' => 'Plans', 'status' => 'Status', 'leaderboard' => 'Leaderboard', 'docs' => 'Docs', 'community' => 'Community', 'settings' => 'Settings', 'logout' => 'Logout', 'plans_active' => 'Active Plans'],
    'common' => ['all' => 'All', 'active' => 'Active', 'inactive' => 'Inactive', 'status' => 'Status', 'date' => 'Date', 'time' => 'Time', 'actions' => 'Actions', 'action' => 'Action', 'name' => 'Name', 'value' => 'Value', 'field' => 'Field', 'type' => 'Type', 'amount' => 'Amount', 'notes' => 'Notes', 'model' => 'Model', 'tokens' => 'Tokens', 'cost' => 'Cost', 'requests' => 'Requests', 'errors' => 'Errors', 'copy' => 'Copy', 'copied' => 'Copied', 'delete' => 'Delete', 'cancel' => 'Cancel', 'close' => 'Close', 'save' => 'Save', 'detail' => 'Details', 'back' => 'Back', 'search' => 'Search', 'apply' => 'Apply', 'reset' => 'Reset', 'export_csv' => 'Export CSV', 'none' => 'None yet', 'unlimited' => 'Unlimited', 'enable' => 'Enable', 'disable' => 'Disable', 'language' => 'Language', 'account' => 'Account', 'account_menu' => 'Account menu', 'open_menu' => 'Open menu', 'close_menu' => 'Close menu', 'navigation_menu' => 'Navigation menu', 'theme' => 'Change theme', 'light_mode' => 'Switch to light mode', 'dark_mode' => 'Switch to dark mode', 'view_more' => 'View more', 'yes_delete' => 'Yes, delete', 'optional' => 'Optional', 'never' => 'Never', 'total' => 'Total', 'from' => 'From', 'to' => 'To'],
    'topbar' => ['balance' => 'Balance', 'active_balance' => 'Active balance', 'open_inbox' => 'Open inbox', 'view_all' => 'View all', 'open_inbox_link' => 'Open Inbox', 'empty_inbox' => 'No messages yet.'],
    'overview' => ['heading' => 'Overview', 'subtitle' => 'A summary of your Azkia Router account, balance, API keys, and usage.', 'hero' => 'Build with one AI gateway', 'hero_text' => 'Manage API keys, monitor your balance and token usage, and check model status in real time — all from one dashboard.', 'balance' => 'Balance', 'requests' => 'Requests', 'total_requests' => 'Total requests', 'cost' => 'Cost', 'total_cost' => 'Total usage cost', 'quickstart' => 'Quickstart', 'recent_keys' => 'Recent API Keys', 'recent_usage' => 'Recent Usage', 'prefix' => 'Prefix', 'endpoint' => 'Endpoint', 'input_output' => 'Input + output', 'subtitle_dash' => 'A summary of your balance, traffic, tokens, cost, and API health.', 'welcome' => 'Welcome back, :name', 'welcome_text' => 'Monitor today’s usage and compare it with yesterday before opening the full report.', 'manage_keys' => 'Manage API Keys', 'view_usage' => 'View Usage Details', 'topup_balance' => 'Top Up Balance', 'balance_available' => 'Available Balance', 'reserved_keys' => 'Reserved :amount · :count active keys', 'requests_today' => 'Requests Today', 'vs_yesterday' => ':arrow :percent% vs yesterday (:count)', 'vs_yesterday_pct' => ':arrow :percent% vs yesterday', 'tokens_today' => 'Tokens Today', 'tokens_sub' => ':arrow :percent% · :input in / :output out', 'in' => 'in', 'out' => 'out', 'cost_today' => 'Cost Today', 'traffic_hourly' => 'Hourly Traffic', 'today_vs_yesterday' => 'Today vs yesterday', 'today' => 'Today', 'yesterday' => 'Yesterday', 'health_today' => 'Health Today', 'success_rate' => 'Success rate', 'error_rate' => 'Error rate', 'avg_latency' => 'Avg latency', 'last_7_days' => 'Last 7 Days', 'summary_7' => ':requests requests · :tokens tokens', 'summary_7_cost' => ':cost · :count errors', 'top_models_7' => 'Top Models · 7 Days', 'per_model_7' => ':count requests · :cost', 'no_usage' => 'No usage yet.', 'name' => 'Name', 'usage_7_days' => '7-day usage', 'req_short' => ':count req', 'token_short' => ':count tokens', 'no_keys' => 'No API keys yet.', 'recent_requests' => 'Recent Requests', 'all_requests' => 'All Requests', 'model_endpoint' => 'Model / Endpoint', 'no_requests' => 'No requests yet.', 'chart_title' => ':label: :count requests'],
    'status' => ['operational' => 'Operational', 'degraded' => 'Degraded', 'offline' => 'Offline', 'down' => 'Down', 'no_pricing' => 'No pricing', 'no_data' => 'No data', 'paid' => 'Paid', 'unpaid' => 'Unpaid', 'failed' => 'Failed', 'expired' => 'Expired', 'refund' => 'Refund', 'completed' => 'Completed', 'pending' => 'Pending', 'read' => 'read', 'new' => 'new'],
    'flash' => ['profile_updated' => 'Profile updated successfully.', 'message_deleted' => 'Message deleted successfully.', 'messages_deleted' => 'All messages deleted successfully.', 'messages_read' => 'All messages marked as read.', 'key_toggled' => 'API key status updated.', 'key_expiry_removed' => 'API key expiry removed.', 'key_deleted' => 'API key deleted.', 'payment_unavailable' => 'The payment method is unavailable.', 'below_minimum' => 'The amount is below the channel minimum.', 'above_maximum' => 'The amount exceeds the channel maximum.', 'payment_failed' => 'Payment could not be created: :message', 'channels_failed' => 'Payment methods could not be loaded: :message', 'gateway_http' => 'The gateway responded with HTTP :status', 'gateway_unreachable' => 'The gateway could not be reached: :message', 'insufficient_balance' => 'Insufficient balance — please top up first.', 'plan_purchased' => 'The :plan plan has been activated. The quota can be used immediately.', 'payg_updated' => 'PAYG mode updated.', 'plan_sold_out' => 'This plan is sold out.'],
    'footer' => ['legal' => 'Legal information', 'terms' => 'Terms & Conditions', 'privacy' => 'Privacy Policy', 'community' => 'Community'],
    'landing' => [
        'meta_title' => 'Azkia Router — One Gateway for All AI Models',
        'meta_description' => 'Route requests to various AI models through a single API key. OpenAI-compatible, automatic billing, rate limiting, and usage monitoring.',
        'logo_alt' => 'Azkia Router logo',
        'nav' => ['models' => 'Models', 'features' => 'Features', 'how' => 'How It Works', 'pricing' => 'Pricing', 'tools' => 'Tools', 'api' => 'API', 'payment' => 'Payment'],
        'login' => 'Log In',
        'get_started' => 'Get Started Free',
        'language' => 'Change language',
        'hero_badge' => 'AI API Gateway · Pay As You Go',
        'hero_title_1' => 'One API key for',
        'hero_title_2' => 'many AI models.',
        'hero_sub' => 'Build AI applications through an OpenAI-compatible API. Pick a model, top up online, and monitor tokens and costs from one dashboard.',
        'cta_start' => 'Start Now',
        'cta_docs' => 'View Documentation',
        'meta_payg' => 'Pay as you use',
        'meta_topup' => 'Top up via Tripay',
        'meta_sdk' => 'OpenAI SDK works out of the box',
        'code_comment' => '# OpenAI SDK, just change base_url',
        'models' => ['heading' => 'Available Models', 'sub' => 'Choose from various AI models with transparent capabilities and pricing.', 'icon_alt' => ':model icon', 'context' => 'Context window', 'tokens' => ':count tokens', 'input' => 'Input / 1M', 'output' => 'Output / 1M', 'empty' => 'No active models', 'empty_hint' => 'No models have been enabled yet.', 'show_all' => 'Show all models (:count)', 'show_less' => 'Show fewer', 'get_access' => 'Get Access'],
        'plans' => ['heading' => 'Flexible token plans', 'sub' => 'Buy token quotas with your balance — plan usage is used first, then PAYG kicks in when it runs out.', 'badge_free' => 'Free', 'daily_quota' => 'Daily quota', 'reset' => 'Reset', 'reset_daily' => 'Automatic daily', 'price' => 'Price', 'free' => 'Free', 'free_hint' => 'No card, no initial balance', 'register_free' => 'Sign Up Free', 'models_label' => 'Models:', 'total_quota' => 'Total quota', 'daily_limit' => 'Daily limit', 'rate_limit' => 'Rate limit', 'rate_per_min' => ':count/min', 'valid' => 'Valid for', 'stock' => 'Stock', 'sold_out' => 'Sold out', 'stock_left' => ':count left', 'buy' => 'Sign Up & Buy', 'empty' => 'No paid plans are active yet — check back later.', 'payg_note' => 'Plan quota exhausted? Enable <strong>PAYG</strong> in the dashboard — keep using your balance and pay per token used.'],
        'features' => ['heading' => 'Everything you need', 'sub' => 'Focus on building your app — let Azkia handle the AI model infrastructure.', 'f1' => ['t' => 'OpenAI Compatible', 'd' => 'Use your existing OpenAI library — just change the base_url and API key.'], 'f2' => ['t' => 'PAYG & Online Top Up', 'd' => 'Pay per token used and top up through Tripay payment channels.'], 'f3' => ['t' => 'Rate Limiting', 'd' => 'Control requests per minute and monthly token quotas for every API key.'], 'f4' => ['t' => 'Multi-Model Catalog', 'd' => 'Pick models by capability: chat, tools, vision, audio, completion, or embedding.'], 'f5' => ['t' => 'Usage & Audit Log', 'd' => 'Monitor usage charts, models, tokens, cost, cache, latency, status, and request IDs.'], 'f6' => ['t' => 'Streaming & Cache', 'd' => 'SSE responses for responsive chat plus gateway caching for repeated requests.']],
        'steps' => ['heading' => 'How it works', 'sub' => 'From signup to your first request in under 5 minutes.', 's1' => ['t' => 'Create an account', 'd' => 'Sign up to the dashboard and browse model catalogs, capabilities, status, and pricing.'], 's2' => ['t' => 'Top up & create an API key', 'd' => 'Top up via Tripay, then create an API key with the quota and expiry you need.'], 's3' => ['t' => 'Connect your app', 'd' => 'Use the Azkia Router <code>base_url</code> with the OpenAI SDK or your favorite HTTP client.']],
        'payment' => ['heading' => 'Easy top-up, balance arrives automatically', 'sub' => 'Pick an active payment channel, complete the payment through Tripay, then use your balance for API requests.', 'f1' => ['t' => 'Multiple Channels', 'd' => 'Payment methods follow the Tripay merchant’s active channels, including virtual accounts, QRIS, and more.'], 'f2' => ['t' => 'Automatic Balance', 'd' => 'Once the payment is verified, your balance is added automatically without manual confirmation.'], 'f3' => ['t' => 'Secure Verification', 'd' => 'Payment callbacks are verified with a signature and processed idempotently to prevent duplicate credits.']],
        'api' => ['heading' => 'API Documentation', 'sub' => 'Endpoints fully compatible with OpenAI — no need to learn a new API.', 'intro' => 'Main endpoints available:', 'd_models' => 'List models', 'd_chat' => 'Chat AI', 'd_text' => 'Text', 'd_embedding' => 'Embedding', 'docs_hint' => 'Full documentation is available on the <strong>Docs</strong> page after logging in.'],
        'tools' => ['heading' => 'Compatible with your favorite tools', 'cat_agent' => 'Agent · Terminal', 'cat_vscode' => 'VS Code extension', 'cat_ide' => 'IDE extension', 'cat_desktop' => 'Desktop app', 'cat_chat' => 'Chat app', 'cat_web' => 'Self-hosted web', 'cta' => 'Try Now'],
        'cta' => ['heading' => 'Ready to build your AI app?', 'sub' => 'Create an account, top up your balance, generate an API key, and access various models through one gateway.', 'button' => 'Create Account'],
    ],
];

$pages = [
    'keys' => ['subtitle' => 'Create, manage, and monitor API keys for your applications.', 'new_secret' => 'New secret key created', 'secret_once' => 'Copy it now — this secret is shown only once and cannot be viewed again.', 'total_keys' => 'Total Keys', 'active_keys' => 'Active Keys', 'create' => 'Create API Key', 'monthly_quota' => 'Monthly quota (tokens)', 'no_expiry' => 'No expiration', 'expires_at' => 'Expires on', 'create_button' => 'Create key', 'security' => 'Security', 'security_text' => 'API keys are used as Bearer tokens. Never put keys in frontends, mobile apps, public repositories, or application logs. Rotate a leaked key by deleting it and creating a new one.', 'your_keys' => 'Your Keys', 'empty' => 'No API keys yet', 'empty_hint' => 'Create your first key using the form above to start using the gateway.', 'quota' => 'Quota', 'expires' => 'Expires', 'usage' => 'Usage', 'last_used' => 'Last Used', 'expired' => 'Expired', 'soon' => 'Soon', 'unused' => 'Not used yet', 'remove_expiry' => 'Remove this key’s expiration', 'delete_title' => 'Delete API key?', 'delete_text' => 'The :name key will be deleted immediately and can no longer be used. All requests using this key will fail afterward.', 'this_key' => 'this key', 'bearer_auth' => 'Bearer Auth'],
    'usage' => ['heading' => 'Request Log', 'subtitle' => 'A complete audit of every API request — key, model, tokens, cost, latency, IP, and user agent.', 'audit_log' => 'Audit Log', 'avg_latency' => 'average latency :value ms', 'daily_activity' => 'Daily Activity', 'daily_hint' => 'Last 14 days — select a metric to view its trend', 'chart_metric' => 'Chart metric', 'last_14_days' => 'Last 14 days', 'empty_14' => 'No usage in the last 14 days.', 'per_model' => 'Usage by Model', 'model_hint' => 'Last 30 days — 8 models with the highest cost', 'model_metric' => 'Metric by model', 'empty_30' => 'No usage in the last 30 days.', 'all_keys' => 'All keys', 'success_filter' => 'Success (<400)', 'error_filter' => 'Error (≥400)', 'request_log' => 'Request Log', 'input_output' => 'Tokens (in/out)', 'cache' => 'Cache', 'latency' => 'Latency', 'empty' => 'No request data', 'empty_hint' => 'No requests match these filters. Change the filters or make your first request through the API gateway.', 'view_detail' => 'View request details :id', 'detail' => 'Request Details', 'ip_address' => 'IP Address', 'user_agent' => 'User Agent', 'ip' => 'IP', 'cache_hit' => 'hit', 'cache_write' => 'write', 'unit_token' => 'tokens', 'unit_request' => 'requests', 'unit_error' => 'errors', 'unit_in' => 'in', 'unit_out' => 'out', 'area_aria' => '14-day activity trend chart', 'area_total_label' => 'Total', 'area_total' => 'Total: :count tokens', 'request_and_error' => ':requests requests · :errors errors'],
    'billing' => ['subtitle' => 'Pay As You Go — your balance is automatically charged based on each model’s token usage.', 'balance_text' => 'Your active account balance. Every API request is automatically charged based on the price per million tokens.', 'topup' => 'Top Up Balance', 'rate' => 'Real-time rate: 1 USD = :rate (source: open.er-api.com)', 'month_requests' => 'Requests This Month', 'month_tokens' => 'Tokens This Month', 'month_cost' => 'Cost This Month', 'average_request' => 'average :cost/request', 'estimated_requests' => 'Estimated Requests Remaining', 'estimate_basis' => 'based on the average billable request this month', 'model_prices' => 'Model Pricing (per 1 million tokens)', 'no_models' => 'No active models yet.', 'calculator' => 'Cost Calculator', 'input_tokens' => 'Input tokens', 'output_tokens' => 'Output tokens', 'example' => 'e.g. :value', 'request_estimate' => 'Estimated request cost', 'estimate_hint' => 'Estimate = price per 1 million tokens × tokens used. Actual cost is calculated from actual usage.', 'input_1m' => 'Input / 1M', 'output_1m' => 'Output / 1M', 'cache_read_1m' => 'Cache Read / 1M', 'cache_write_1m' => 'Cache Write / 1M', 'topup_history' => 'Top-up History', 'new_topup' => 'New Top Up', 'reference' => 'Reference', 'method' => 'Method', 'nominal' => 'Amount', 'total_payment' => 'Total Payment', 'empty_topup' => 'No top-up history yet.', 'latest_ledger' => 'Recent Balance Ledger', 'balance_after' => 'Balance After', 'empty_ledger' => 'No balance changes yet.'],
    'plans' => ['heading' => 'Token Plans', 'subtitle' => 'Buy token quotas with your balance — plan usage is prioritized before PAYG.', 'payg_title' => 'PAYG Mode (Pay As You Go)', 'payg_hint' => 'When enabled and the plan quota runs out, usage continues from your balance at standard prices. When disabled, requests are rejected once the plan quota runs out.', 'payg_on' => 'PAYG enabled', 'payg_off' => 'PAYG disabled', 'payg_enable' => 'Enable PAYG', 'payg_disable' => 'Disable PAYG', 'balance' => 'Your balance', 'plan_tokens' => 'Active plan quota left', 'purchase_title' => 'Buy a Plan', 'tokens_total' => 'Total quota', 'daily_limit' => 'Daily limit', 'rate_limit' => 'Rate limit', 'duration' => 'Valid for', 'price_idr' => 'IDR price', 'price_usd' => 'USD price', 'buy' => 'Buy Now', 'buy_hint' => 'Charged from your USD balance :price. No refund — tokens expire when the plan expires.', 'confirm_title' => 'Confirm Purchase', 'confirm_yes' => 'Yes, Buy', 'no_plans' => 'No plans available yet.', 'history_title' => 'My Plan History', 'remaining' => 'Left', 'used' => 'Used', 'expires' => 'Expires', 'purchased' => 'Purchased', 'status_label' => 'Status', 'empty_history' => 'No plan purchases yet.', 'free_hint' => 'Free for every user — the quota resets automatically every day (server time).', 'free_remaining' => 'Left today', 'free_per_day' => 'of :tokens per day', 'no_expiry' => 'No expiry', 'free_active' => 'Active · Free', 'free_badge' => 'Free', 'expired' => 'Expired', 'plan_col' => 'Plan', 'tokens_left' => ':used / :total tokens left', 'percent_left' => ':percent% left', 'stock' => 'Stock', 'stock_left' => ':stock left', 'sold_out' => 'Sold out', 'usage' => 'Usage'],
    'models' => ['subtitle' => 'A catalog of public model aliases for your OpenAI-compatible requests.', 'online' => ':count models online', 'search_placeholder' => 'Search models, providers, or upstream...', 'search_label' => 'Search models', 'capability_filter' => 'Filter model capabilities', 'sort_label' => 'Sort models', 'sort_name' => 'Sort: Name', 'sort_context' => 'Sort: Context', 'sort_price' => 'Sort: Lowest price', 'icon_alt' => ':model icon', 'promo_title' => 'Model is on promotion', 'promo' => 'Promo', 'context_window' => 'Context window', 'cache_read_hint' => 'Input price when tokens are served from the provider cache', 'cache_write_hint' => 'Price per token written to cache', 'copy_alias' => 'Copy alias', 'show_example' => 'Show example', 'hide_example' => 'Hide example', 'empty' => 'No active models', 'empty_hint' => 'No models have been enabled by an administrator.', 'no_results' => 'No results', 'no_results_hint' => 'No models match your search or filters.'],
    'status' => ['subtitle' => 'Real-time model availability.', 'active_models' => ':count active models', 'summary' => ':models active models · :requests requests · :errors errors', 'last_check' => 'last checked · automatically every 10 minutes', 'live_unavailable' => 'Real-time ping unavailable: :error — status is shown from usage data.', 'search_placeholder' => 'Search models...', 'filter' => 'Filter status', 'average_usage' => 'average usage', 'not_used' => 'never used', 'no_requests' => 'none yet', 'uptime' => 'Uptime', 'latency' => 'Latency', 'history' => 'History for the last 5 hours', 'empty_filter' => 'No models match the filter.', 'legend' => 'Last 5 hours · every 10 minutes — hover over a box for details', 'no_request' => 'No requests', 'no_active_heading' => 'No active models', 'no_active_text' => 'No models have been activated by the admin yet.', 'legend_ok' => 'OK', 'legend_error' => 'Error', 'legend_down' => 'Down', 'legend_no_request' => 'No requests'],
    'leaderboard' => ['heading' => 'Model Leaderboard', 'subtitle' => 'The most-used models, ranked by total tokens.', 'models' => ':count models', 'total_tokens' => 'Total Tokens', 'total_requests' => 'Total Requests', 'total_cost' => 'Total Cost', 'all_usage' => 'all usage', 'selected_range' => 'in the selected range', 'range' => 'Time range:', 'all_time' => 'All time', 'last_30' => 'Last 30 days', 'last_7' => 'Last 7 days', 'today' => 'Today', 'calculation' => 'Rankings are calculated from total tokens.', 'last_used' => 'Last used :time', 'never_used' => 'never used', 'rank' => 'Rank :rank', 'rank_col' => '#', 'model_col' => 'Model', 'requests_col' => 'Requests', 'tokens_col' => 'Total Tokens', 'tokens_total' => ':count tokens total', 'champion_1' => '🥇 Champion 1 — most used', 'champion_2' => '🥈 Champion 2', 'champion_3' => '🥉 Champion 3', 'empty' => 'No usage in the selected time range.'],
    'docs' => ['heading' => 'Developer Docs', 'subtitle' => 'Quickstart guide for using the Azkia Router API.', 'base_hint' => 'Use this as base_url in the OpenAI SDK.', 'authentication' => 'Authentication', 'auth_hint' => 'Create a key on the API Keys page. Send the key as a Bearer token.', 'streaming_hint' => 'Set stream: true — the response is sent as SSE (Server-Sent Events), and cost is calculated after the stream finishes.', 'endpoints' => 'Endpoints', 'method' => 'Method', 'path' => 'Path', 'description' => 'Description', 'list_models' => 'List available active models', 'chat' => 'Chat completions (supports streaming)', 'errors' => 'Error Codes', 'meaning' => 'Meaning', 'text_completions' => 'Text completions', 'embeddings' => 'Embeddings', 'base_url' => 'Base URL', 'python' => 'Python', 'curl' => 'cURL', 'nodejs' => 'Node.js', 'streaming' => 'Streaming', 'err_400' => 'Bad request — unsupported model endpoint or capability (for example vision or tools)', 'err_401' => 'Invalid, missing, or expired API key', 'err_402' => 'Insufficient balance, monthly quota exceeded, or missing model pricing', 'err_403' => 'User suspended', 'err_404' => 'Model not found or inactive', 'err_429' => 'Rate limit exceeded', 'err_503' => 'Gateway unavailable', 'tools' => ['heading' => 'Coding Tools & AI Agents', 'intro' => 'All of these tools support OpenAI-compatible APIs — just fill in your Base URL and API key. The model you use must be an active public alias (see the Model catalog).', 'cat_agent_terminal' => 'Coding agent · Terminal', 'cat_vscode' => 'VS Code extension', 'cat_vscode_jetbrains' => 'VS Code / JetBrains extension', 'cat_desktop' => 'Desktop app', 'cat_chat' => 'Chat app (desktop/web)', 'cat_web' => 'Self-hosted web UI', 'how_cline' => 'Settings → API Provider: <strong>OpenAI Compatible</strong><br>Base URL: <code>:url</code><br>Enter your API key and model alias.', 'how_roo' => 'Same as Cline: pick the <strong>OpenAI Compatible</strong> provider, fill in the Base URL <code>:url</code>, API key, and model.', 'how_continue' => 'Add a model with the <strong>OpenAI</strong> provider:<br>apiBase: <code>:url</code><br>apiKey + your model alias.', 'how_cherry' => 'Settings → Model Provider → <strong>OpenAI</strong>:<br>Base URL: <code>:url</code>', 'how_chatbox' => 'Settings → Model Provider → <strong>OpenAI API</strong>:<br>API Host: <code>:url</code>', 'how_webui' => 'Settings → Connections → <strong>OpenAI API</strong>:<br>API Base URL: <code>:url</code>', 'how_librechat' => 'Add an OpenAI-compatible endpoint with the Base URL <code>:url</code> and your API key.']],
    'inbox' => ['heading' => 'Inbox', 'mark_all' => 'Mark all as read', 'delete_all' => 'Delete all', 'delete_all_confirm' => 'Delete all inbox messages? This action cannot be undone.', 'from' => 'From Azkia Router · :date', 'mark_read' => 'Mark as read', 'delete_confirm' => 'Delete this message?', 'empty' => 'Your inbox is empty.'],
    'settings' => ['heading' => 'Settings', 'subtitle' => 'Manage your account profile.', 'profile' => 'Profile', 'profile_hint' => 'The name and email displayed in your dashboard.', 'full_name' => 'Full name', 'save_profile' => 'Save Profile', 'account_id' => 'Account ID: #:id', 'email' => 'Email'],
    'redeem_code' => ['heading' => 'Redeem Code', 'code_label' => 'Redeem code', 'redeem' => 'Redeem Code'],
    'topup' => ['heading' => 'Top Up Balance', 'subtitle' => 'Choose an amount and a Tripay payment method.', 'back' => 'Back to Billing', 'gateway_hint' => 'Make sure the Tripay credentials are configured.', 'amount' => 'Top-up Amount (IDR)', 'minimum' => 'Minimum :amount. Balance is converted to USD using the exchange rate when the transaction is created.', 'phone' => 'WhatsApp / Phone Number', 'phone_example' => 'Example: 081234567890', 'phone_hint' => 'Used by Tripay to process certain payment methods.', 'method' => 'Payment Method', 'channel_minimum' => ':group · min :amount', 'continue' => 'Continue to Payment'],
    'payment' => ['heading' => 'Payment Details', 'pay_code' => 'Payment code / Virtual Account', 'qr_alt' => 'Payment QR', 'open_app' => 'Open Payment App', 'pay_tripay' => 'Pay through Tripay', 'success' => 'Payment successful. The balance has been added.', 'summary' => 'Summary', 'balance_amount' => 'Balance amount', 'fee' => 'Payment fee', 'total' => 'Total payment', 'received' => 'Balance received', 'expires' => 'Expires at', 'back' => 'Back to Billing'],
    'api_health' => ['heading' => 'API Health', 'subtitle' => 'Azkia Router gateway status.', 'live' => 'Live status', 'unreachable' => 'Gateway is unreachable', 'checked' => 'Uptime :uptime · Latency :latency ms · Checked :date', 'details' => 'Details', 'empty_details' => 'No details available.', 'empty' => 'No health data yet.'],
    'support' => ['heading' => 'Support Center', 'subtitle' => 'Manage your questions and account support.', 'create_ticket' => 'Create Ticket', 'number' => 'Number', 'subject' => 'Subject', 'category' => 'Category', 'last' => 'Last activity', 'empty' => 'No tickets yet.', 'create_heading' => 'Create Ticket', 'create_subtitle' => 'Do not include API keys, passwords, or sensitive data.', 'back' => 'Back', 'subject_label' => 'Subject', 'category_label' => 'Category', 'request_reference' => 'Request reference (optional)', 'billing_event' => 'Billing event (optional)', 'payment_order' => 'Payment order (optional)', 'message' => 'Message', 'attachments' => 'Images (optional, max 3)', 'send' => 'Send Ticket', 'details' => 'Details', 'priority' => 'Priority: :value', 'request' => 'Request: :value', 'billing' => 'Billing', 'event' => 'Event: :value', 'payment' => 'Payment', 'order' => 'Order: :value', 'you' => 'You', 'support_role' => 'Support', 'reply' => 'Reply', 'send_reply' => 'Send Reply', 'closed' => 'This ticket has been closed and can no longer be replied to.', 'cat_technical' => 'Technical', 'cat_billing' => 'Billing', 'cat_payment' => 'Payment', 'cat_account' => 'Account', 'cat_api_key' => 'API Key', 'cat_model' => 'Model', 'cat_other' => 'Other', 'st_open' => 'Open', 'st_closed' => 'Closed', 'st_pending' => 'Pending', 'st_awaiting_support' => 'Awaiting Support', 'st_awaiting_user' => 'Awaiting You', 'st_resolved' => 'Resolved'],
];
$overrides['pages'] = $pages;

return array_replace_recursive($id, $overrides);
