@extends('layouts.app')
@section('content')
@php
$change = function ($current, $previous) { if ((float) $previous === 0.0) return (float) $current > 0 ? 100 : 0; return round(((float) $current - (float) $previous) / (float) $previous * 100, 1); };
$reqChange = $change($today->requests, $yesterday->requests); $tokenChange = $change($today->input_tokens + $today->output_tokens, $yesterday->input_tokens + $yesterday->output_tokens); $costChange = $change($today->cost, $yesterday->cost); $errorRate = $today->requests ? round($today->errors / $today->requests * 100, 2) : 0; $previousErrorRate = $yesterday->requests ? round($yesterday->errors / $yesterday->requests * 100, 2) : 0; $reportedTotal = (int) $breakdown->reported + (int) $breakdown->estimated; $reportedRate = $reportedTotal ? round($breakdown->reported / $reportedTotal * 100, 1) : 0; $cacheBase = max(1, (int) $today->requests); $maxModel = max(1, (int) ($topModels->max('requests') ?? 1));
@endphp
<style>
.ops-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.ops-stat{padding:17px}.ops-label{font-size:12px;color:var(--muted);font-weight:700;text-transform:uppercase;letter-spacing:.04em}.ops-value{font-size:25px;font-weight:800;margin:7px 0 3px}.ops-delta{font-size:12px}.ops-up{color:#16a34a}.ops-down{color:#dc2626}.ops-grid{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(280px,.8fr);gap:16px}.ops-chart{height:270px;position:relative}.ops-chart svg{width:100%;height:100%;overflow:visible}.ops-gridline{stroke:var(--line);stroke-width:1}.ops-axis{fill:var(--muted);font-size:10px}.ops-line-today{fill:none;stroke:#2563eb;stroke-width:3}.ops-line-yesterday{fill:none;stroke:#94a3b8;stroke-width:2;stroke-dasharray:6 5}.ops-point{fill:var(--card);stroke:#2563eb;stroke-width:2}.ops-legend{display:flex;gap:16px;font-size:12px;color:var(--muted)}.ops-legend i{display:inline-block;width:18px;height:3px;margin-right:6px;vertical-align:middle}.ops-bars{display:grid;gap:14px}.ops-bar-head{display:flex;justify-content:space-between;font-size:12px}.ops-track{height:9px;background:var(--line);border-radius:8px;overflow:hidden;margin-top:6px}.ops-fill{height:100%;background:#2563eb;border-radius:8px}.ops-fill.green{background:#16a34a}.ops-fill.amber{background:#f59e0b}.ops-fill.red{background:#dc2626}.rank-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;padding:10px 0;border-bottom:1px solid var(--line)}.rank-row:last-child{border:0}.rank-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.rank-meta{font-size:11px;color:var(--muted)}
@media(max-width:1000px){.ops-stats{grid-template-columns:repeat(2,1fr)}.ops-grid{grid-template-columns:1fr}}@media(max-width:600px){.ops-stats{grid-template-columns:1fr}}
</style>
<div class="top"><div><h2>Request Logs</h2><p>Observabilitas trafik, token, biaya, kualitas usage, cache, dan request seluruh user.</p></div><span class="pill">{{ number_format($logs->total()) }} request</span></div>
<div class="ops-stats">
<div class="card ops-stat"><div class="ops-label">Request Hari Ini</div><div class="ops-value">{{ number_format($today->requests) }}</div><div class="ops-delta {{ $reqChange >= 0 ? 'ops-up' : 'ops-down' }}">{{ $reqChange >= 0 ? '↑' : '↓' }} {{ abs($reqChange) }}% vs kemarin ({{ number_format($yesterday->requests) }})</div></div>
<div class="card ops-stat"><div class="ops-label">Token Hari Ini</div><div class="ops-value">{{ format_compact_number($today->input_tokens + $today->output_tokens) }}</div><div class="ops-delta {{ $tokenChange >= 0 ? 'ops-up' : 'ops-down' }}">{{ $tokenChange >= 0 ? '↑' : '↓' }} {{ abs($tokenChange) }}% vs kemarin</div><div class="rank-meta">{{ format_compact_number($today->input_tokens) }} in · {{ format_compact_number($today->output_tokens) }} out</div></div>
<div class="card ops-stat"><div class="ops-label">Biaya Hari Ini</div><div class="ops-value">{{ format_idr_usd($today->cost) }}</div><div class="ops-delta {{ $costChange >= 0 ? 'ops-up' : 'ops-down' }}">{{ $costChange >= 0 ? '↑' : '↓' }} {{ abs($costChange) }}% vs kemarin</div></div>
<div class="card ops-stat"><div class="ops-label">Error Rate</div><div class="ops-value">{{ $errorRate }}%</div><div class="ops-delta {{ $errorRate <= $previousErrorRate ? 'ops-up' : 'ops-down' }}">{{ number_format($today->errors) }} error · kemarin {{ $previousErrorRate }}%</div><div class="rank-meta">Avg latency {{ number_format($today->avg_latency) }} ms</div></div>
</div>
<div class="ops-grid section">
<div class="card"><div class="top" style="margin-bottom:8px"><div><h3>Trafik per Jam</h3><p>Hari ini dibanding jam yang sama kemarin</p></div><div class="ops-legend"><span><i style="background:#2563eb"></i>Hari ini</span><span><i style="background:#94a3b8"></i>Kemarin</span></div></div><div id="traffic-chart" class="ops-chart" data-points='@json($hourly)'><svg viewBox="0 0 720 260" preserveAspectRatio="none"></svg></div></div>
<div class="card"><h3>Kesehatan Data Hari Ini</h3><div class="ops-bars"><div><div class="ops-bar-head"><span>Usage reported</span><strong>{{ $reportedRate }}%</strong></div><div class="ops-track"><div class="ops-fill green" style="width:{{ $reportedRate }}%"></div></div></div><div><div class="ops-bar-head"><span>Success rate</span><strong>{{ $today->requests ? round($breakdown->successful / $today->requests * 100, 1) : 0 }}%</strong></div><div class="ops-track"><div class="ops-fill" style="width:{{ $today->requests ? round($breakdown->successful / $today->requests * 100, 1) : 0 }}%"></div></div></div><div><div class="ops-bar-head"><span>Cache hit</span><strong>{{ round($breakdown->cache_hits / $cacheBase * 100, 1) }}%</strong></div><div class="ops-track"><div class="ops-fill amber" style="width:{{ min(100, round($breakdown->cache_hits / $cacheBase * 100, 1)) }}%"></div></div></div><div><div class="ops-bar-head"><span>Error</span><strong>{{ $errorRate }}%</strong></div><div class="ops-track"><div class="ops-fill red" style="width:{{ min(100, $errorRate) }}%"></div></div></div></div><p class="rank-meta" style="margin-top:18px">{{ number_format($breakdown->reported) }} reported · {{ number_format($breakdown->estimated) }} estimated · {{ number_format($breakdown->cache_hits) }} cache hit · {{ number_format($breakdown->cache_writes) }} cache write</p></div>
</div>
<div class="grid2 section"><div class="card"><h3>Top Model Hari Ini</h3>@forelse($topModels as $row)<div class="rank-row"><div><div class="rank-name">{{ $row->model }}</div><div class="ops-track"><div class="ops-fill" style="width:{{ round($row->requests/$maxModel*100) }}%"></div></div><div class="rank-meta">{{ format_compact_number($row->tokens) }} token · {{ format_idr_usd($row->cost) }} · {{ $row->errors }} error</div></div><strong>{{ number_format($row->requests) }}</strong></div>@empty<p class="muted">Belum ada trafik hari ini.</p>@endforelse</div><div class="card"><h3>Top User Hari Ini</h3>@forelse($topUsers as $row)<div class="rank-row"><div><div class="rank-name">{{ $row->email ?: 'User dihapus' }}</div><div class="rank-meta">{{ format_compact_number($row->tokens) }} token · {{ format_idr_usd($row->cost) }}</div></div><strong>{{ number_format($row->requests) }}</strong></div>@empty<p class="muted">Belum ada trafik hari ini.</p>@endforelse</div></div>
<div class="card section compact"><form method="get"><div class="grid3"><div><label>Cari ID / endpoint / email / key</label><input name="search" value="{{ request('search') }}"></div><div><label>User</label><select name="user_id"><option value="">Semua user</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string) request('user_id') === (string) $user->id)>{{ $user->email }}</option>@endforeach</select></div><div><label>Model</label><select name="model"><option value="">Semua model</option>@foreach($models as $model)<option value="{{ $model }}" @selected(request('model') === $model)>{{ $model }}</option>@endforeach</select></div><div><label>Status</label><select name="status"><option value="">Semua</option><option value="success" @selected(request('status') === 'success')>Success</option><option value="error" @selected(request('status') === 'error')>Error</option></select></div><div><label>Source</label><select name="source"><option value="">Semua</option>@foreach($sources as $source)<option value="{{ $source }}" @selected(request('source') === $source)>{{ $source }}</option>@endforeach</select></div><div><label>Quality</label><select name="quality"><option value="">Semua</option><option value="reported" @selected(request('quality') === 'reported')>Reported</option><option value="estimated" @selected(request('quality') === 'estimated')>Estimated</option></select></div><div><label>Cache</label><select name="cache"><option value="">Semua</option><option value="read" @selected(request('cache') === 'read')>Hit</option><option value="write" @selected(request('cache') === 'write')>Write</option><option value="none" @selected(request('cache') === 'none')>Tanpa cache</option></select></div><div><label>Dari</label><input type="date" name="from" value="{{ request('from') }}"></div><div><label>Sampai</label><input type="date" name="to" value="{{ request('to') }}"></div></div><button>Terapkan</button> <a class="btn secondary" href="{{ route('admin.request-logs.index') }}">Reset</a></form></div>
<div class="section table-wrap"><table><thead><tr><th>Waktu / ID</th><th>User / Key</th><th>Model / Endpoint</th><th>Token</th><th>Cost / Latency</th><th>Status</th><th>Usage / Cache</th><th>Aksi</th></tr></thead><tbody>@forelse($logs as $log)<tr><td><strong>{{ $log->created_at?->format('d M H:i:s') }}</strong><br><span class="muted">{{ $log->request_id ?: '—' }}</span></td><td>{{ $log->user?->email ?: '—' }}<br><span class="muted">{{ $log->apiKey?->name ?: '—' }} · {{ $log->apiKey?->prefix ?: '—' }}</span></td><td>{{ $log->model }}<br><span class="muted">{{ $log->endpoint }}</span></td><td>{{ number_format($log->input_tokens) }} in<br>{{ number_format($log->output_tokens) }} out</td><td>${{ $log->cost }}<br><span class="muted">{{ $log->latency_ms !== null ? number_format($log->latency_ms).' ms' : '—' }}</span></td><td><span class="badge {{ ($log->status_code ?? 500) >= 400 ? 'red' : 'green' }}">{{ $log->status_code ?? '—' }}</span></td><td>{{ $log->usage_source }} · {{ $log->usage_quality }}<br><span class="muted">{{ $log->cache_read ? 'hit' : ($log->cache_write ? 'write' : 'none') }}</span></td><td><a class="btn secondary" href="{{ route('admin.request-logs.show', ['usageLog' => $log->id]) }}">Detail</a></td></tr>@empty<tr><td colspan="8" class="muted">Tidak ada request log.</td></tr>@endforelse</tbody></table></div>{{ $logs->links() }}
<script>(function(){var el=document.getElementById('traffic-chart');if(!el)return;var d=JSON.parse(el.dataset.points||'[]'),svg=el.querySelector('svg'),w=720,h=260,l=38,r=12,t=15,b=28,max=Math.max(1,...d.map(x=>Math.max(x.today,x.yesterday))),uw=w-l-r,uh=h-t-b,coords=k=>d.map((x,i)=>({x:l+i*uw/23,y:t+uh-(x[k]/max*uh)})),path=c=>c.map((p,i)=>(i?'L':'M')+p.x.toFixed(1)+' '+p.y.toFixed(1)).join(' '),a=coords('today'),z=coords('yesterday'),html='';[0,.25,.5,.75,1].forEach(q=>{var y=t+uh*q;html+='<line class="ops-gridline" x1="'+l+'" y1="'+y+'" x2="'+(w-r)+'" y2="'+y+'"/><text class="ops-axis" x="'+(l-6)+'" y="'+(y+3)+'" text-anchor="end">'+Math.round(max*(1-q))+'</text>'});d.forEach((x,i)=>{if(i%3===0)html+='<text class="ops-axis" x="'+a[i].x+'" y="'+(h-7)+'" text-anchor="middle">'+x.label+'</text>'});html+='<path class="ops-line-yesterday" d="'+path(z)+'"/><path class="ops-line-today" d="'+path(a)+'"/>';a.forEach((p,i)=>html+='<circle class="ops-point" cx="'+p.x+'" cy="'+p.y+'" r="3"><title>'+d[i].label+': '+d[i].today+' request, '+d[i].errors+' error, '+d[i].tokens+' token</title></circle>');svg.innerHTML=html})();</script>
@endsection
